spring.application.name=campus-backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=SuperSecretPassw0rd123!
spring.jpa.hibernate.ddl-auto=update
